#############################################################################
# Makefile for building: Measurelogic
# Generated by qmake (2.01a) (Qt 4.8.0) on: Fri Mar 9 16:26:19 2018
# Project:  Measurelogic.pro
# Template: app
# Command: /opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/bin/qmake -spec /opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/qws/linux-arm-M283 CONFIG+=release -o Makefile Measurelogic.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-fsl-linux-gnueabi-gcc
CXX           = arm-fsl-linux-gnueabi-g++
DEFINES       = 
CFLAGS        = -pipe -O2 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W $(DEFINES)
INCPATH       = -I/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/qws/linux-arm-M283 -I. -IInterfaceInclude -ICppSqlite3 -IInterfaceInclude/CppSqlite3 -ICommon
LINK          = arm-fsl-linux-gnueabi-g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/lib
LIBS          = $(SUBLIBS)   -lpthread -ldl 
AR            = arm-fsl-linux-gnueabi-ar cqs
RANLIB        = 
QMAKE         = /opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = arm-fsl-linux-gnueabi-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		SINYD_DBModule/DBTableQueryRow.cpp \
		SINYD_DBModule/DBTableConfigTool.cpp \
		SINYD_DBModule/DBTable.cpp \
		SINYD_DBModule/DBController.cpp \
		SINYD_Measure/Data/RWData/RWData.cpp \
		SINYD_Measure/Tool/syd_time.cpp \
		SINYD_Measure/Tool/syd_record_file.cpp \
		SINYD_Measure/main/machine_loader.cpp \
		SINYD_Measure/main/data_provider.cpp \
		SINYD_Measure/main/data_node.cpp \
		SINYD_Measure/main/data_collector.cpp \
		SINYD_Measure/main/data_node/valued_hopper_node.cpp \
		SINYD_Measure/main/data_node/raw_recorder.cpp \
		SINYD_Measure/main/data_node/multivalued_hopper_node.cpp \
		SINYD_Measure/main/data_node/mixer_node.cpp \
		SINYD_Measure/main/data_node/hopper_product.cpp \
		SINYD_Measure/main/data_node/hopper_node.cpp \
		SINYD_Measure/main/data_provider/can_data_provider.cpp \
		SINYD_Measure/main/data_provider/analog_calibrator.cpp \
		SINYD_Measure/main/machine_loader/cement_machine_loader.cpp \
		CppSqlite3/sqlite3.c \
		CppSqlite3/CppSQLite3.cpp \
		SINYD_Measure/main/data_provider/rawfile_playback.cpp \
		SINYD_Measure/main/data_node/rawdb_recorder.cpp \
		SINYD_DBModule/DBOperator.cpp \
		SINYD_DBModule/DBModule.cpp \
		lib_Json/json_writer.cpp \
		lib_Json/json_value.cpp \
		lib_Json/json_reader.cpp \
		TinyXML2/tinyxml2.cpp \
		SINYD_DataTransfer/TransDataReader.cpp \
		SINYD_DataTransfer/SYDDataTransferImpl.cpp \
		SINYD_DataTransfer/SYDDataTransfer.cpp \
		SINYD_DataTransfer/SocketWrapper.cpp \
		SINYD_DataTransfer/SocketAPI.cpp \
		SINYD_DataTransfer/ReturnCodeParser.cpp \
		SINYD_DataTransfer/JsonRW.cpp \
		SINYD_DataTransfer/DBFileGetter.cpp \
		SINYD_DataTransfer/DataBreakPointStorage.cpp \
		SINYD_DataTransfer/TRWData.cpp \
		SINYD_DBModule/DBHandleManager.cpp \
		SINYD_Measure/main/data_provider/rawdb_playback.cpp \
		SINYD_Measure/main/data_algorithm/data_algorithm.cpp \
		SINYD_Measure/main/abstract_algorithm.cpp \
		SINYD_Measure/Data/data_node_valuemgr.cpp \
		SINYD_Measure/main/data_node/valuedbytap_hopper_node.cpp \
		SINYD_DataTransfer/TransDataReader_Flume.cpp \
		SINYD_DataTransfer/FlumeDataRW.cpp \
		SINYD_DataTransfer/ConfigGetter.cpp \
		SINYD_DataTransfer/TransConfig.cpp 
OBJECTS       = main.o \
		DBTableQueryRow.o \
		DBTableConfigTool.o \
		DBTable.o \
		DBController.o \
		RWData.o \
		syd_time.o \
		syd_record_file.o \
		machine_loader.o \
		data_provider.o \
		data_node.o \
		data_collector.o \
		valued_hopper_node.o \
		raw_recorder.o \
		multivalued_hopper_node.o \
		mixer_node.o \
		hopper_product.o \
		hopper_node.o \
		can_data_provider.o \
		analog_calibrator.o \
		cement_machine_loader.o \
		sqlite3.o \
		CppSQLite3.o \
		rawfile_playback.o \
		rawdb_recorder.o \
		DBOperator.o \
		DBModule.o \
		json_writer.o \
		json_value.o \
		json_reader.o \
		tinyxml2.o \
		TransDataReader.o \
		SYDDataTransferImpl.o \
		SYDDataTransfer.o \
		SocketWrapper.o \
		SocketAPI.o \
		ReturnCodeParser.o \
		JsonRW.o \
		DBFileGetter.o \
		DataBreakPointStorage.o \
		TRWData.o \
		DBHandleManager.o \
		rawdb_playback.o \
		data_algorithm.o \
		abstract_algorithm.o \
		data_node_valuemgr.o \
		valuedbytap_hopper_node.o \
		TransDataReader_Flume.o \
		FlumeDataRW.o \
		ConfigGetter.o \
		TransConfig.o
DIST          = /opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/common/unix.conf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/common/linux.conf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/common/gcc-base.conf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/common/gcc-base-unix.conf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/common/g++-base.conf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/common/g++-unix.conf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/common/qws.conf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/qconfig.pri \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/qt_functions.prf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/qt_config.prf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/exclusive_builds.prf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/default_pre.prf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/release.prf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/default_post.prf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/warn_on.prf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/resources.prf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/uic.prf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/yacc.prf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/lex.prf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/include_source_dir.prf \
		Measurelogic.pro
QMAKE_TARGET  = Measurelogic
DESTDIR       = 
TARGET        = Measurelogic

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Measurelogic.pro  /opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/qws/linux-arm-M283/qmake.conf /opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/common/unix.conf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/common/linux.conf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/common/gcc-base.conf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/common/gcc-base-unix.conf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/common/g++-base.conf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/common/g++-unix.conf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/common/qws.conf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/qconfig.pri \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/qt_functions.prf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/qt_config.prf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/exclusive_builds.prf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/default_pre.prf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/release.prf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/default_post.prf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/warn_on.prf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/resources.prf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/uic.prf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/yacc.prf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/lex.prf \
		/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/qws/linux-arm-M283 CONFIG+=release -o Makefile Measurelogic.pro
/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/common/unix.conf:
/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/common/linux.conf:
/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/common/gcc-base.conf:
/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/common/gcc-base-unix.conf:
/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/common/g++-base.conf:
/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/common/g++-unix.conf:
/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/common/qws.conf:
/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/qconfig.pri:
/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/qt_functions.prf:
/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/qt_config.prf:
/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/exclusive_builds.prf:
/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/default_pre.prf:
/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/release.prf:
/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/default_post.prf:
/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/warn_on.prf:
/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/resources.prf:
/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/uic.prf:
/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/yacc.prf:
/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/lex.prf:
/opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /opt/gcc-4.4.4-glibc-2.11.1-multilib-1.0/arm-fsl-linux-gnueabi/mkspecs/qws/linux-arm-M283 CONFIG+=release -o Makefile Measurelogic.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Measurelogic1.0.0 || $(MKDIR) .tmp/Measurelogic1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Measurelogic1.0.0/ && (cd `dirname .tmp/Measurelogic1.0.0` && $(TAR) Measurelogic1.0.0.tar Measurelogic1.0.0 && $(COMPRESS) Measurelogic1.0.0.tar) && $(MOVE) `dirname .tmp/Measurelogic1.0.0`/Measurelogic1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Measurelogic1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp SINYD_Measure/main/data_collector.h \
		SINYD_Measure/main/data_provider.h \
		SINYD_Measure/Include/SwDscuMmdef.h \
		SINYD_Measure/Include/EmsasCommon.h \
		SINYD_Measure/Tool/syd_time.h \
		SINYD_Measure/main/data_node.h \
		SINYD_Measure/Data/RWData/RWData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

DBTableQueryRow.o: SINYD_DBModule/DBTableQueryRow.cpp SINYD_DBModule/DBTableQueryRow.h \
		SINYD_DBModule/DBModulePrivate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DBTableQueryRow.o SINYD_DBModule/DBTableQueryRow.cpp

DBTableConfigTool.o: SINYD_DBModule/DBTableConfigTool.cpp SINYD_DBModule/DBTableConfigTool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DBTableConfigTool.o SINYD_DBModule/DBTableConfigTool.cpp

DBTable.o: SINYD_DBModule/DBTable.cpp SINYD_DBModule/DBTable.h \
		SINYD_DBModule/DBModulePrivate.h \
		SINYD_DBModule/DBTableConfigTool.h \
		SINYD_DBModule/DBTableQueryRow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DBTable.o SINYD_DBModule/DBTable.cpp

DBController.o: SINYD_DBModule/DBController.cpp SINYD_DBModule/DBController.h \
		SINYD_DBModule/DBModulePrivate.h \
		SINYD_DBModule/DBTable.h \
		SINYD_DBModule/DBHandleManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DBController.o SINYD_DBModule/DBController.cpp

RWData.o: SINYD_Measure/Data/RWData/RWData.cpp SINYD_Measure/Data/RWData/RWData.h \
		SINYD_Measure/Include/EmsasCommon.h \
		SINYD_Measure/Include/SwDscuMmdef.h \
		SINYD_Measure/Include/DebugLogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RWData.o SINYD_Measure/Data/RWData/RWData.cpp

syd_time.o: SINYD_Measure/Tool/syd_time.cpp SINYD_Measure/Include/DebugLogger.h \
		SINYD_Measure/Tool/syd_time.h \
		SINYD_Measure/Include/SwDscuMmdef.h \
		SINYD_Measure/Include/EmsasCommon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o syd_time.o SINYD_Measure/Tool/syd_time.cpp

syd_record_file.o: SINYD_Measure/Tool/syd_record_file.cpp SINYD_Measure/Tool/syd_record_file.h \
		SINYD_Measure/Tool/syd_time.h \
		SINYD_Measure/Include/SwDscuMmdef.h \
		SINYD_Measure/Include/EmsasCommon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o syd_record_file.o SINYD_Measure/Tool/syd_record_file.cpp

machine_loader.o: SINYD_Measure/main/machine_loader.cpp SINYD_Measure/main/machine_loader.h \
		SINYD_Measure/main/data_node.h \
		SINYD_Measure/main/data_provider.h \
		SINYD_Measure/Include/SwDscuMmdef.h \
		SINYD_Measure/Include/EmsasCommon.h \
		SINYD_Measure/Tool/syd_time.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o machine_loader.o SINYD_Measure/main/machine_loader.cpp

data_provider.o: SINYD_Measure/main/data_provider.cpp SINYD_Measure/main/data_provider.h \
		SINYD_Measure/Include/SwDscuMmdef.h \
		SINYD_Measure/Include/EmsasCommon.h \
		SINYD_Measure/Tool/syd_time.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o data_provider.o SINYD_Measure/main/data_provider.cpp

data_node.o: SINYD_Measure/main/data_node.cpp SINYD_Measure/main/data_node.h \
		SINYD_Measure/main/data_provider.h \
		SINYD_Measure/Include/SwDscuMmdef.h \
		SINYD_Measure/Include/EmsasCommon.h \
		SINYD_Measure/Tool/syd_time.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o data_node.o SINYD_Measure/main/data_node.cpp

data_collector.o: SINYD_Measure/main/data_collector.cpp SINYD_Measure/main/data_collector.h \
		SINYD_Measure/main/data_provider.h \
		SINYD_Measure/Include/SwDscuMmdef.h \
		SINYD_Measure/Include/EmsasCommon.h \
		SINYD_Measure/Tool/syd_time.h \
		SINYD_Measure/main/data_node.h \
		SINYD_Measure/main/data_provider/can_data_provider.h \
		SINYD_Measure/main/data_provider/analog_calibrator.h \
		SINYD_Measure/main/data_provider/rawfile_playback.h \
		SINYD_Measure/main/data_provider/rawdb_playback.h \
		SINYD_Measure/main/machine_loader.h \
		SINYD_Measure/main/machine_loader/cement_machine_loader.h \
		SINYD_Measure/main/data_node/mixer_node.h \
		SINYD_Measure/main/data_node/hopper_node.h \
		SINYD_Measure/main/data_node/hopper_product.h \
		SINYD_Measure/Tool/syd_record_file.h \
		SINYD_Measure/main/data_node/valued_hopper_node.h \
		SINYD_Measure/Data/Include/Operation_conf.h \
		SINYD_Measure/Include/DebugLogger.h \
		SINYD_Measure/main/data_algorithm/data_algorithm.h \
		SINYD_Measure/Data/data_node_valuemgr.h \
		SINYD_Measure/main/data_node/rawdb_recorder.h \
		SINYD_Measure/Data/RWData/RWData.h \
		SINYD_Measure/main/data_provider/sc_data_provider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o data_collector.o SINYD_Measure/main/data_collector.cpp

valued_hopper_node.o: SINYD_Measure/main/data_node/valued_hopper_node.cpp SINYD_Measure/main/data_node/valued_hopper_node.h \
		SINYD_Measure/main/data_node/hopper_node.h \
		SINYD_Measure/main/data_node.h \
		SINYD_Measure/main/data_provider.h \
		SINYD_Measure/Include/SwDscuMmdef.h \
		SINYD_Measure/Include/EmsasCommon.h \
		SINYD_Measure/Tool/syd_time.h \
		SINYD_Measure/main/data_node/hopper_product.h \
		SINYD_Measure/Data/Include/Operation_conf.h \
		SINYD_Measure/Include/DebugLogger.h \
		SINYD_Measure/main/data_algorithm/data_algorithm.h \
		SINYD_Measure/Data/data_node_valuemgr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o valued_hopper_node.o SINYD_Measure/main/data_node/valued_hopper_node.cpp

raw_recorder.o: SINYD_Measure/main/data_node/raw_recorder.cpp SINYD_Measure/main/data_node/raw_recorder.h \
		SINYD_Measure/main/data_node.h \
		SINYD_Measure/main/data_provider.h \
		SINYD_Measure/Include/SwDscuMmdef.h \
		SINYD_Measure/Include/EmsasCommon.h \
		SINYD_Measure/Tool/syd_time.h \
		SINYD_Measure/Tool/syd_record_file.h \
		SINYD_Measure/Include/DebugLogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o raw_recorder.o SINYD_Measure/main/data_node/raw_recorder.cpp

multivalued_hopper_node.o: SINYD_Measure/main/data_node/multivalued_hopper_node.cpp SINYD_Measure/main/data_node/multivalued_hopper_node.h \
		SINYD_Measure/main/data_node/valued_hopper_node.h \
		SINYD_Measure/main/data_node/hopper_node.h \
		SINYD_Measure/main/data_node.h \
		SINYD_Measure/main/data_provider.h \
		SINYD_Measure/Include/SwDscuMmdef.h \
		SINYD_Measure/Include/EmsasCommon.h \
		SINYD_Measure/Tool/syd_time.h \
		SINYD_Measure/main/data_node/hopper_product.h \
		SINYD_Measure/Data/Include/Operation_conf.h \
		SINYD_Measure/Include/DebugLogger.h \
		SINYD_Measure/main/data_algorithm/data_algorithm.h \
		SINYD_Measure/Data/data_node_valuemgr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o multivalued_hopper_node.o SINYD_Measure/main/data_node/multivalued_hopper_node.cpp

mixer_node.o: SINYD_Measure/main/data_node/mixer_node.cpp SINYD_Measure/main/data_node/mixer_node.h \
		SINYD_Measure/main/data_node/hopper_node.h \
		SINYD_Measure/main/data_node.h \
		SINYD_Measure/main/data_provider.h \
		SINYD_Measure/Include/SwDscuMmdef.h \
		SINYD_Measure/Include/EmsasCommon.h \
		SINYD_Measure/Tool/syd_time.h \
		SINYD_Measure/main/data_node/hopper_product.h \
		SINYD_Measure/Tool/syd_record_file.h \
		SINYD_Measure/Include/DebugLogger.h \
		SINYD_Measure/Data/RWData/RWData.h \
		SINYD_Measure/Data/Include/Operation_conf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mixer_node.o SINYD_Measure/main/data_node/mixer_node.cpp

hopper_product.o: SINYD_Measure/main/data_node/hopper_product.cpp SINYD_Measure/main/data_node/hopper_product.h \
		SINYD_Measure/Include/EmsasCommon.h \
		SINYD_Measure/Include/SwDscuMmdef.h \
		SINYD_Measure/Tool/syd_time.h \
		SINYD_Measure/Include/DebugLogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hopper_product.o SINYD_Measure/main/data_node/hopper_product.cpp

hopper_node.o: SINYD_Measure/main/data_node/hopper_node.cpp SINYD_Measure/main/data_node/hopper_node.h \
		SINYD_Measure/main/data_node.h \
		SINYD_Measure/main/data_provider.h \
		SINYD_Measure/Include/SwDscuMmdef.h \
		SINYD_Measure/Include/EmsasCommon.h \
		SINYD_Measure/Tool/syd_time.h \
		SINYD_Measure/main/data_node/hopper_product.h \
		SINYD_Measure/Include/DebugLogger.h \
		SINYD_Measure/main/data_node/mixer_node.h \
		SINYD_Measure/Tool/syd_record_file.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hopper_node.o SINYD_Measure/main/data_node/hopper_node.cpp

can_data_provider.o: SINYD_Measure/main/data_provider/can_data_provider.cpp SINYD_Measure/main/data_provider/can_data_provider.h \
		SINYD_Measure/Include/EmsasCommon.h \
		SINYD_Measure/Include/SwDscuMmdef.h \
		SINYD_Measure/main/data_provider.h \
		SINYD_Measure/Tool/syd_time.h \
		SINYD_Measure/main/data_provider/analog_calibrator.h \
		SINYD_Measure/Include/DebugLogger.h \
		SINYD_Measure/Data/RWData/RWData.h \
		SINYD_Measure/Data/Include/Operation_conf.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o can_data_provider.o SINYD_Measure/main/data_provider/can_data_provider.cpp

analog_calibrator.o: SINYD_Measure/main/data_provider/analog_calibrator.cpp SINYD_Measure/Include/DebugLogger.h \
		SINYD_Measure/Data/RWData/RWData.h \
		SINYD_Measure/Include/EmsasCommon.h \
		SINYD_Measure/Include/SwDscuMmdef.h \
		SINYD_Measure/main/data_provider/analog_calibrator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o analog_calibrator.o SINYD_Measure/main/data_provider/analog_calibrator.cpp

cement_machine_loader.o: SINYD_Measure/main/machine_loader/cement_machine_loader.cpp SINYD_Measure/Include/DebugLogger.h \
		SINYD_Measure/Include/EmsasCommon.h \
		SINYD_Measure/Include/SwDscuMmdef.h \
		SINYD_Measure/Data/RWData/RWData.h \
		SINYD_Measure/Data/Include/Operation_conf.h \
		SINYD_Measure/Tool/syd_time.h \
		SINYD_Measure/main/data_provider.h \
		SINYD_Measure/main/data_node/mixer_node.h \
		SINYD_Measure/main/data_node/hopper_node.h \
		SINYD_Measure/main/data_node.h \
		SINYD_Measure/main/data_node/hopper_product.h \
		SINYD_Measure/Tool/syd_record_file.h \
		SINYD_Measure/main/data_node/multivalued_hopper_node.h \
		SINYD_Measure/main/data_node/valued_hopper_node.h \
		SINYD_Measure/main/data_algorithm/data_algorithm.h \
		SINYD_Measure/Data/data_node_valuemgr.h \
		SINYD_Measure/main/data_node/valuedbytap_hopper_node.h \
		SINYD_Measure/main/abstract_algorithm.h \
		SINYD_Measure/main/machine_loader/cement_machine_loader.h \
		SINYD_Measure/main/machine_loader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cement_machine_loader.o SINYD_Measure/main/machine_loader/cement_machine_loader.cpp

sqlite3.o: CppSqlite3/sqlite3.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o sqlite3.o CppSqlite3/sqlite3.c

CppSQLite3.o: CppSqlite3/CppSQLite3.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CppSQLite3.o CppSqlite3/CppSQLite3.cpp

rawfile_playback.o: SINYD_Measure/main/data_provider/rawfile_playback.cpp SINYD_Measure/main/data_provider/rawfile_playback.h \
		SINYD_Measure/main/data_provider.h \
		SINYD_Measure/Include/SwDscuMmdef.h \
		SINYD_Measure/Include/EmsasCommon.h \
		SINYD_Measure/Tool/syd_time.h \
		SINYD_Measure/Include/DebugLogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rawfile_playback.o SINYD_Measure/main/data_provider/rawfile_playback.cpp

rawdb_recorder.o: SINYD_Measure/main/data_node/rawdb_recorder.cpp SINYD_Measure/main/data_node/rawdb_recorder.h \
		SINYD_Measure/main/data_node.h \
		SINYD_Measure/main/data_provider.h \
		SINYD_Measure/Include/SwDscuMmdef.h \
		SINYD_Measure/Include/EmsasCommon.h \
		SINYD_Measure/Tool/syd_time.h \
		SINYD_Measure/Tool/syd_record_file.h \
		SINYD_Measure/Include/DebugLogger.h \
		SINYD_Measure/Data/RWData/RWData.h \
		SINYD_Measure/main/data_provider/can_data_provider.h \
		SINYD_Measure/main/data_provider/analog_calibrator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rawdb_recorder.o SINYD_Measure/main/data_node/rawdb_recorder.cpp

DBOperator.o: SINYD_DBModule/DBOperator.cpp SINYD_DBModule/DBOperator.h \
		SINYD_DBModule/DBModulePrivate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DBOperator.o SINYD_DBModule/DBOperator.cpp

DBModule.o: SINYD_DBModule/DBModule.cpp SINYD_DBModule/DBOperator.h \
		SINYD_DBModule/DBModulePrivate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DBModule.o SINYD_DBModule/DBModule.cpp

json_writer.o: lib_Json/json_writer.cpp lib_Json/json_tool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o json_writer.o lib_Json/json_writer.cpp

json_value.o: lib_Json/json_value.cpp lib_Json/json_valueiterator.inl
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o json_value.o lib_Json/json_value.cpp

json_reader.o: lib_Json/json_reader.cpp lib_Json/json_tool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o json_reader.o lib_Json/json_reader.cpp

tinyxml2.o: TinyXML2/tinyxml2.cpp TinyXML2/tinyxml2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tinyxml2.o TinyXML2/tinyxml2.cpp

TransDataReader.o: SINYD_DataTransfer/TransDataReader.cpp SINYD_DataTransfer/TransDataReader.h \
		SINYD_DataTransfer/DBFileGetter.h \
		SINYD_DataTransfer/DataBreakPointStorage.h \
		TinyXML2/tinyxml2.h \
		SINYD_DataTransfer/JsonRW.h \
		SINYD_DataTransfer/TRWData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TransDataReader.o SINYD_DataTransfer/TransDataReader.cpp

SYDDataTransferImpl.o: SINYD_DataTransfer/SYDDataTransferImpl.cpp SINYD_DataTransfer/SYDDataTransferImpl.h \
		SINYD_DataTransfer/SocketThread.h \
		SINYD_DataTransfer/SocketWrapper.h \
		SINYD_DataTransfer/SocketAPI.h \
		SINYD_DataTransfer/platform.h \
		SINYD_DataTransfer/TransDataReader.h \
		SINYD_DataTransfer/DBFileGetter.h \
		SINYD_DataTransfer/DataBreakPointStorage.h \
		TinyXML2/tinyxml2.h \
		SINYD_DataTransfer/JsonRW.h \
		SINYD_DataTransfer/ReturnCodeParser.h \
		SINYD_DataTransfer/TRWData.h \
		SINYD_DataTransfer/TransConfig.h \
		SINYD_DataTransfer/FlumeDataRW.h \
		SINYD_DataTransfer/TransDataReader_Flume.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SYDDataTransferImpl.o SINYD_DataTransfer/SYDDataTransferImpl.cpp

SYDDataTransfer.o: SINYD_DataTransfer/SYDDataTransfer.cpp SINYD_DataTransfer/SYDDataTransferImpl.h \
		SINYD_DataTransfer/SocketThread.h \
		SINYD_DataTransfer/SocketWrapper.h \
		SINYD_DataTransfer/SocketAPI.h \
		SINYD_DataTransfer/platform.h \
		SINYD_DataTransfer/TransDataReader.h \
		SINYD_DataTransfer/DBFileGetter.h \
		SINYD_DataTransfer/DataBreakPointStorage.h \
		TinyXML2/tinyxml2.h \
		SINYD_DataTransfer/JsonRW.h \
		SINYD_DataTransfer/ReturnCodeParser.h \
		SINYD_DataTransfer/TRWData.h \
		SINYD_DataTransfer/TransConfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SYDDataTransfer.o SINYD_DataTransfer/SYDDataTransfer.cpp

SocketWrapper.o: SINYD_DataTransfer/SocketWrapper.cpp SINYD_DataTransfer/SocketWrapper.h \
		SINYD_DataTransfer/SocketAPI.h \
		SINYD_DataTransfer/platform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SocketWrapper.o SINYD_DataTransfer/SocketWrapper.cpp

SocketAPI.o: SINYD_DataTransfer/SocketAPI.cpp SINYD_DataTransfer/SocketAPI.h \
		SINYD_DataTransfer/platform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SocketAPI.o SINYD_DataTransfer/SocketAPI.cpp

ReturnCodeParser.o: SINYD_DataTransfer/ReturnCodeParser.cpp SINYD_DataTransfer/ReturnCodeParser.h \
		SINYD_DataTransfer/SocketWrapper.h \
		SINYD_DataTransfer/SocketAPI.h \
		SINYD_DataTransfer/platform.h \
		SINYD_DataTransfer/ProtocolDef.h \
		SINYD_DataTransfer/JsonRW.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ReturnCodeParser.o SINYD_DataTransfer/ReturnCodeParser.cpp

JsonRW.o: SINYD_DataTransfer/JsonRW.cpp SINYD_DataTransfer/JsonRW.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JsonRW.o SINYD_DataTransfer/JsonRW.cpp

DBFileGetter.o: SINYD_DataTransfer/DBFileGetter.cpp SINYD_DataTransfer/DBFileGetter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DBFileGetter.o SINYD_DataTransfer/DBFileGetter.cpp

DataBreakPointStorage.o: SINYD_DataTransfer/DataBreakPointStorage.cpp SINYD_DataTransfer/DataBreakPointStorage.h \
		TinyXML2/tinyxml2.h \
		SINYD_DataTransfer/TRWData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DataBreakPointStorage.o SINYD_DataTransfer/DataBreakPointStorage.cpp

TRWData.o: SINYD_DataTransfer/TRWData.cpp SINYD_DataTransfer/TRWData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TRWData.o SINYD_DataTransfer/TRWData.cpp

DBHandleManager.o: SINYD_DBModule/DBHandleManager.cpp SINYD_DBModule/DBHandleManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DBHandleManager.o SINYD_DBModule/DBHandleManager.cpp

rawdb_playback.o: SINYD_Measure/main/data_provider/rawdb_playback.cpp SINYD_Measure/main/data_provider/rawdb_playback.h \
		SINYD_Measure/main/data_provider.h \
		SINYD_Measure/Include/SwDscuMmdef.h \
		SINYD_Measure/Include/EmsasCommon.h \
		SINYD_Measure/Tool/syd_time.h \
		SINYD_Measure/Include/DebugLogger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rawdb_playback.o SINYD_Measure/main/data_provider/rawdb_playback.cpp

data_algorithm.o: SINYD_Measure/main/data_algorithm/data_algorithm.cpp SINYD_Measure/main/data_algorithm/data_algorithm.h \
		SINYD_Measure/Data/Include/Operation_conf.h \
		SINYD_Measure/Include/EmsasCommon.h \
		SINYD_Measure/Include/DebugLogger.h \
		SINYD_Measure/Tool/syd_time.h \
		SINYD_Measure/Include/SwDscuMmdef.h \
		SINYD_Measure/main/data_provider.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o data_algorithm.o SINYD_Measure/main/data_algorithm/data_algorithm.cpp

abstract_algorithm.o: SINYD_Measure/main/abstract_algorithm.cpp SINYD_Measure/main/abstract_algorithm.h \
		SINYD_Measure/Data/Include/Operation_conf.h \
		SINYD_Measure/Include/EmsasCommon.h \
		SINYD_Measure/Include/DebugLogger.h \
		SINYD_Measure/Tool/syd_time.h \
		SINYD_Measure/Include/SwDscuMmdef.h \
		SINYD_Measure/main/data_provider.h \
		SINYD_Measure/main/data_algorithm/data_algorithm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o abstract_algorithm.o SINYD_Measure/main/abstract_algorithm.cpp

data_node_valuemgr.o: SINYD_Measure/Data/data_node_valuemgr.cpp SINYD_Measure/Data/data_node_valuemgr.h \
		SINYD_Measure/Data/Include/Operation_conf.h \
		SINYD_Measure/Include/EmsasCommon.h \
		SINYD_Measure/Include/DebugLogger.h \
		SINYD_Measure/Tool/syd_time.h \
		SINYD_Measure/Include/SwDscuMmdef.h \
		SINYD_Measure/main/data_provider.h \
		SINYD_Measure/Data/RWData/RWData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o data_node_valuemgr.o SINYD_Measure/Data/data_node_valuemgr.cpp

valuedbytap_hopper_node.o: SINYD_Measure/main/data_node/valuedbytap_hopper_node.cpp SINYD_Measure/main/data_node/valuedbytap_hopper_node.h \
		SINYD_Measure/main/data_node/hopper_node.h \
		SINYD_Measure/main/data_node.h \
		SINYD_Measure/main/data_provider.h \
		SINYD_Measure/Include/SwDscuMmdef.h \
		SINYD_Measure/Include/EmsasCommon.h \
		SINYD_Measure/Tool/syd_time.h \
		SINYD_Measure/main/data_node/hopper_product.h \
		SINYD_Measure/Data/Include/Operation_conf.h \
		SINYD_Measure/Include/DebugLogger.h \
		SINYD_Measure/Data/data_node_valuemgr.h \
		SINYD_Measure/Data/RWData/RWData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o valuedbytap_hopper_node.o SINYD_Measure/main/data_node/valuedbytap_hopper_node.cpp

TransDataReader_Flume.o: SINYD_DataTransfer/TransDataReader_Flume.cpp SINYD_DataTransfer/TransDataReader_Flume.h \
		SINYD_DataTransfer/TransDataReader.h \
		SINYD_DataTransfer/DBFileGetter.h \
		SINYD_DataTransfer/DataBreakPointStorage.h \
		TinyXML2/tinyxml2.h \
		SINYD_DataTransfer/JsonRW.h \
		SINYD_DataTransfer/FlumeDataRW.h \
		SINYD_DataTransfer/TransConfig.h \
		SINYD_DataTransfer/ConfigGetter.h \
		SINYD_DataTransfer/TRWData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TransDataReader_Flume.o SINYD_DataTransfer/TransDataReader_Flume.cpp

FlumeDataRW.o: SINYD_DataTransfer/FlumeDataRW.cpp SINYD_DataTransfer/FlumeDataRW.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FlumeDataRW.o SINYD_DataTransfer/FlumeDataRW.cpp

ConfigGetter.o: SINYD_DataTransfer/ConfigGetter.cpp SINYD_DataTransfer/ConfigGetter.h \
		SINYD_DataTransfer/TRWData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ConfigGetter.o SINYD_DataTransfer/ConfigGetter.cpp

TransConfig.o: SINYD_DataTransfer/TransConfig.cpp SINYD_DataTransfer/TransConfig.h \
		SINYD_DataTransfer/TRWData.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TransConfig.o SINYD_DataTransfer/TransConfig.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

